# Generated by Django 4.0.4 on 2022-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_post_alter_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ManyToManyField(null=True, related_name='children', to='main.comment'),
        ),
    ]
