# Generated by Django 4.0.4 on 2022-04-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_comment_parent_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
